version: '3'

services:
  back:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - "8090:8090"
    volumes:
      - ./backend/:/code
    env_file:
      - ./.env
    depends_on:
      - database
    links:
      - database
    stdin_open: true
    tty: true

  database:
    container_name: database
    image: postgres:latest
    volumes:
      - postgres_data_project:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  postgres_data_project:
